package eu.catlabs.demo.services;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;

@Service
public class AiService {

    private final ChatClient chatClient;
    private final ObjectMapper objectMapper;

    public AiService(ChatClient.Builder chatClientBuilder, ObjectMapper objectMapper) {
        this.chatClient = chatClientBuilder.build();
        this.objectMapper = objectMapper;
    }

    private String extractJsonFromResponse(String response) {
        // Try to extract array first
        int arrayStart = response.indexOf("[");
        int arrayEnd = response.lastIndexOf("]") + 1;

        if (arrayStart >= 0 && arrayEnd > arrayStart) {
            return response.substring(arrayStart, arrayEnd);
        }

        // Fall back to object extraction
        int objectStart = response.indexOf("{");
        int objectEnd = response.lastIndexOf("}") + 1;

        if (objectStart >= 0 && objectEnd > objectStart) {
            return response.substring(objectStart, objectEnd);
        }

        return response;
    }

    public JsonNode createHumans() throws JsonProcessingException {
        return this.prompt("""
                    You are a data generator. 
                    Your job is to strictly return valid JSON array that matches the following structure:
                    {
                      "name": "Albert Einstein",
                      "creativity": 0.5,
                      "intellect": 0.5,
                      "sociability": 0.5,
                      "practicality": 0.5,
                      "personality": "creative"
                    }
                
                    Rules:
                    - Create 10 humans  
                    - The field names must always be: name, creativity, intellect, sociability, practicality, personality.
                    - The values should describe a fictional human, give a name that is fun in French (Prenom et nom forment un jeu de mots).
                    - creativity, intellect, sociability, practicality should be between 0 and 1 and their sum should be 2.
                    - personality should be a string generated by the amount of creativity, intellect, sociability, practicality and the value should be of type .
                    - Return only valid JSON (no explanation, no Markdown, no extra text).
                """);
    }

    private JsonNode prompt(String prompt) throws JsonProcessingException {
        String response = chatClient.prompt(prompt)
                .call()
                .content();
        String cleanJson = extractJsonFromResponse(response);
        JsonNode jsonNode = objectMapper.readTree(cleanJson);
        System.out.println(jsonNode);
        return jsonNode;
    }

}
