package eu.catlabs.humanaity.ai.application.prompt;

import eu.catlabs.humanaity.ai.domain.AiPrompt;
import org.springframework.stereotype.Component;

/**
 * Builder for creating AI prompts for human generation.
 * Encapsulates the prompt template logic.
 */
@Component
public class HumanGenerationPrompt {
    
    private static final String DEFAULT_LANGUAGE = "French";
    private static final int DEFAULT_COUNT = 5;
    
    /**
     * Create a prompt for generating humans.
     * 
     * @param count Number of humans to generate
     * @param language Language for names (e.g., "French")
     * @return Configured AI prompt
     */
    public AiPrompt createHumanGenerationPrompt(int count, String language) {
        String systemMessage = "You are a data generator. Your job is to strictly return valid JSON array.";
        
        String userMessage = String.format("""
            Create %d humans with the following structure:
            {
              "name": "Albert Einstein",
              "creativity": 0.5,
              "intellect": 0.5,
              "sociability": 0.5,
              "practicality": 0.5,
              "personality": "creative"
            }
            
            Rules:
            - Create %d humans.
            - The field names must always be: name, creativity, intellect, sociability, practicality, personality.
            - The values should describe a fictional human, give a name that is fun in %s (Prenom et nom forment un jeu de mots).
            - creativity, intellect, sociability, practicality should be between 0 and 1 and their sum should be 2.
            - personality should be a string generated by the amount of creativity, intellect, sociability, practicality.
            - Return only valid JSON (no explanation, no Markdown, no extra text).
            """, count, count, language);
        
        return AiPrompt.builder()
                .systemMessage(systemMessage)
                .userMessage(userMessage)
                .responseFormat(AiPrompt.ResponseFormat.JSON_ARRAY)
                .build();
    }
    
    /**
     * Create a prompt for generating humans with default settings.
     * 
     * @return Configured AI prompt
     */
    public AiPrompt createHumanGenerationPrompt() {
        return createHumanGenerationPrompt(DEFAULT_COUNT, DEFAULT_LANGUAGE);
    }
    
    /**
     * Create a prompt for generating interactions.
     * (Currently not used, but kept for future use)
     */
    public AiPrompt createInteractionPrompt() {
        String systemMessage = "You are a data generator. Return JSON only, no markdown, no explanation.";
        
        String userMessage = """
            Return JSON only, no markdown, no explanation. Begin with [ and end with ].
            Your job is to strictly return valid JSON array that matches the following structure:
            {
              "type": "INVENTION",
              "creativity": 0.5,
              "intellect": 0.5,
              "sociability": 0.5,
              "practicality": 0.5,
              "personality": "creative"
            }
            
            Rules:
            - Create 2 humans.
            - The field names must always be: name, creativity, intellect, sociability, practicality, personality.
            - The values should describe a fictional human, give a name that is fun in French (Prenom et nom forment un jeu de mots).
            - creativity, intellect, sociability, practicality should be between 0 and 1 and their sum should be 2.
            - personality should be a string generated by the amount of creativity, intellect, sociability, practicality.
            - Return only valid JSON (no explanation, no Markdown, no extra text).
            """;
        
        return AiPrompt.builder()
                .systemMessage(systemMessage)
                .userMessage(userMessage)
                .responseFormat(AiPrompt.ResponseFormat.JSON_ARRAY)
                .build();
    }
}
